//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmovi
    {
        public Filmovi()
        {
            this.Ocjenes = new HashSet<Ocjene>();
            this.Zanrovis = new HashSet<Zanrovi>();
            this.Projekcijes = new HashSet<Projekcije>();
            this.Komentaris = new HashSet<Komentari>();
        }
    
        public int FilmID { get; set; }
        public string Naziv { get; set; }
        public string Glumci { get; set; }
        public string Opis { get; set; }
        public bool Akrivan { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public System.DateTime DatumModifikacije { get; set; }
        public double IMDBOcjena { get; set; }
        public double Ocjena { get; set; }
        public byte[] Slika { get; set; }
    
        public virtual ICollection<Ocjene> Ocjenes { get; set; }
        public virtual ICollection<Zanrovi> Zanrovis { get; set; }
        public virtual ICollection<Projekcije> Projekcijes { get; set; }
        public virtual ICollection<Komentari> Komentaris { get; set; }
    }
}
