//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_Api.Models
{
    using System;
    
    public partial class KomentariVM
    {
        public string Komentar { get; set; }
        public string KorisnickoIme { get; set; }
        public string DatumKreiranja { get; set; }
        public int KomentarID { get; set; }
    }
}
