//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentari
    {
        public int KomentarID { get; set; }
        public string Komentar { get; set; }
        public int KorisnikID { get; set; }
        public int FilmID { get; set; }
        public Nullable<int> KomentarKomentaraID { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
    
        public virtual Filmovi Filmovi { get; set; }
        public virtual Korisnici Korisnici { get; set; }
    }
}
