//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Novosti
    {
        public int NovostID { get; set; }
        public byte[] Slika { get; set; }
        public string Naslov { get; set; }
        public string Sadrzaj { get; set; }
        public Nullable<bool> Aktivno { get; set; }
        public Nullable<System.DateTime> DatumKreiranja { get; set; }
    }
}
