//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacije
    {
        public int RezervacijaID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
        public Nullable<int> ProjekcijaID { get; set; }
        public Nullable<int> SjedisteID { get; set; }
        public Nullable<System.DateTime> DatumRezervacije { get; set; }
        public Nullable<bool> Otkazano { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Projekcije Projekcije { get; set; }
        public virtual Sjedista Sjedista { get; set; }
    }
}
