//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sjedista
    {
        public Sjedista()
        {
            this.Rezervacijes = new HashSet<Rezervacije>();
        }
    
        public int SjedisteID { get; set; }
        public string Red { get; set; }
        public Nullable<int> BrojSjedista { get; set; }
    
        public virtual ICollection<Rezervacije> Rezervacijes { get; set; }
    }
}
