//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipProjekcije
    {
        public TipProjekcije()
        {
            this.Projekcijes = new HashSet<Projekcije>();
        }
    
        public int TipID { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Projekcije> Projekcijes { get; set; }
    }
}
