//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eKino_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zanrovi
    {
        public Zanrovi()
        {
            this.Filmovis = new HashSet<Filmovi>();
        }
    
        public int ZanrID { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Filmovi> Filmovis { get; set; }
    }
}
